### PR TITLE
fixes regex on safari match for pro plus spa

### PR DESCRIPTION
**Pull request by passion4code**
Fixes snippet of output of `proAndSpaAgent` causing syntax error to be thrown

Old: `a=/Version\\/(\\S+)\\s+Safari/;`

New: `a=/Version\/(\S+)\s+Safari/;`

Old pattern throws a syntax error when attempting to be used. 

The "new" pattern is the same as what's being used in the "pro"

### CODE REVIEW

**Comment by passion4code** [comment]
@tangollama for your merging pleasure :)

**Comment by jakemhiller** [comment]
Just noticed this error in our application when trying out the plubin, is there an ETA on an NPM version with this fix?

**Comment by passion4code** [comment]
Pretty please :) `npm publish` :)

**Comment by devfreddy** [comment]
@jakemhiller @passion4code A fix to 1.X has been published on npm. There's an even better implementation in progress in https://github.com/newrelic/gatsby-plugin-newrelic/pull/10 which will ensure this is a non-issue in the future and keeps everything up to date.

**Pull request merged**
