### PR TITLE
Support gatsby 4

### PR DESCRIPTION
**Pull request by herecydev**
### Acceptance Criteria

- [x] Review PR and approve 
- [ ] creating an alpha release of this package[ on NPM](https://www.npmjs.com/package/gatsby-build-newrelic)
- [ ] provide that to @herecydev for testing purposes
- [ ] If testing passes, then publish this version to NPM as a new version release.

### CODE REVIEW

**Comment by herecydev** [comment]
It's been a month and literally no movement on this? @devfreddy

**Comment by jpvajda** [comment]
@herecydev sorry for the delay, let me review this out for you.

**Comment by jpvajda** [comment]
@herecydev have you validated this change to plugin solves your problem reported in the linked issue? It's a very simple change but I'm curious how to best test it with your site to ensure this will all that is required to enable the plugin to support Gatsby 4.

**Comment by herecydev** [comment]
I haven't, I did check against what's changed and couldn't find anything relevant. However if you did want to push an alpha out I would happily confirm that it solves the issues and continues to function. I know that it still works because I _do_ already use this against Gatsby 4. It just throws warnings..

**Comment by jpvajda** [comment]
@herecydev much of our team is on holiday leave at the moment so we were going to look at creating an alpha package on NPM in early January for the plugin, would that work for you?

**Comment by jpvajda** [comment]
For context I added some Acceptance Criteria so the team knows the next steps on this PR @zstix

**Comment by herecydev** [comment]
@jpvajda yer that's fine for me

**Comment by jpvajda** [comment]
I've reached out to @devfreddy on the process to release an alpha version of this package on NPM.

**Comment by jpvajda** [comment]
closing this in favor of this PR https://github.com/newrelic/gatsby-plugin-newrelic/pull/45

**Pull request closed without merging**
