### PR TITLE
fix: javascript had a bad value in liteAgent causing issues

### PR DESCRIPTION
**Pull request by shawncarr**
Hoping to address issue #2. The issue was a non-escaped regex definition

### CODE REVIEW

**Comment by GuillaumeAmat** [comment]
Hey @tangollama, any chance for you to look at this soon?

**Comment by danielgolden** [comment]
Hi @shawncarr. Sorry for the delay 😓 . We'll definitely take a look at this. I'll reach out to our team now to get this PR reviewed. Thanks for submitting this!

**Comment by tangollama** [comment]
@shawncarr thanks for the PR. Merging. @GuillaumeAmat look for a new release shortly.

**Comment by GuillaumeAmat** [comment]
@tangollama any news on the new release? Hopefully including the #8?

**Comment by passion4code** [comment]
@tangollama @GuillaumeAmat  Bump  (and +1 to include #8)

**Comment by tangollama** [comment]
@passion4code @GuillaumeAmat this was merged already. I'll take a look at #8.

**Comment by GuillaumeAmat** [comment]
Sure @tangollama, but not published...

**Comment by devfreddy** [comment]
This has been published to npm in https://www.npmjs.com/package/gatsby-plugin-newrelic/v/1.0.3.

[We're also working on a 2.x version](https://github.com/newrelic/gatsby-plugin-newrelic/pull/10) that includes the necessary JS via CDN, which is more reliable (and arguably more performant).

**Comment by passion4code** [comment]
Awesome, thanks!

**Pull request merged**
